---
- hosts: web
  become: true
  tasks:
    - name: Install docker
      yum: name=docker state=present update_cache=yes

    - name: Install docker compose
      vars:
        ansible_user: ec2-user
      get_url:
        url : https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'

    - name: Execute service docker
      service:
        name: docker 
        enabled: true
        state: started

    - name: Copy docker-compose
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user

    - name: Add user to docker
      user:
        name: ec2-user
        groups: docker

    - name: Deploy springrest docker compose
      shell: /usr/local/bin/docker-compose up -d --no-build
