---
- name: Install httpd
  yum: name=httpd state=present update_cache=yes

- name: Start httpd
  service: 
    name: httpd 
    enabled: true
    state: started
        
- name: Install vue-2048
  copy:
    src: ~/vue-2048/dist/
    dest: /var/www/html